// COMPREHENSIVE TEST LEADS - 5 Different Leads with Complete Data
// Use this in your N8N Function node to test all features

const testLeads = [
  {
    // === LEAD 1: HIGH-VALUE URGENT LEAD ===
    "lead_id": "LEAD_001",
    "property_id": "PROP_001",
    "address": "123 Oak Street, Chicago, IL 60614",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60614",
    "contact_name": "John Smith",
    "phone": "312-555-0123",
    "email": "john.smith@email.com",
    "property_value": 750000,
    "purchase_price": 720000,
    "market_value": 750000,
    "year_built": 2019,
    "building_sqft": 3500,
    "lot_size_sqft": 13068,
    "lot_size_acres": 0.3,
    "bedrooms": 4,
    "bathrooms": 3,
    "property_type": "Single Family",
    "days_since_purchase": 45,
    "mortgage_amount": 576000,
    "property_tax_trend": "increasing",
    "estimated_income": 150000,
    "family_size": 4,
    "school_rating": 9,
    "neighborhood_type": "suburban",
    "neighborhood_value_trend": "increasing",
    "neighborhood_median_income": 120000,
    "competitor_count": 3,
    "population_density": 2500,
    "market_growth_rate": 12,
    "unemployment_rate": 4.2,
    "income_trend": "increasing",
    "market_maturity": "growing",
    "has_pool": true,
    "has_deck": false,
    "has_basement": true,
    "has_hoa": true,
    "num_garages": 2,
    "days_since_permit": 15,
    "days_since_violation": null,
    "business_owner": false
  },
  
  {
    // === LEAD 2: MID-VALUE FAMILY HOME ===
    "lead_id": "LEAD_002",
    "property_id": "PROP_002",
    "address": "456 Pine Avenue, Austin, TX 78701",
    "city": "Austin",
    "state": "TX",
    "zip_code": "78701",
    "contact_name": "Sarah Johnson",
    "phone": "512-555-0456",
    "email": "sarah.johnson@gmail.com",
    "property_value": 450000,
    "purchase_price": 425000,
    "market_value": 450000,
    "year_built": 2015,
    "building_sqft": 2200,
    "lot_size_sqft": 8712,
    "lot_size_acres": 0.2,
    "bedrooms": 3,
    "bathrooms": 2,
    "property_type": "Single Family",
    "days_since_purchase": 120,
    "mortgage_amount": 340000,
    "property_tax_trend": "stable",
    "estimated_income": 95000,
    "family_size": 3,
    "school_rating": 8,
    "neighborhood_type": "urban",
    "neighborhood_value_trend": "stable",
    "neighborhood_median_income": 85000,
    "competitor_count": 7,
    "population_density": 4200,
    "market_growth_rate": 8,
    "unemployment_rate": 3.8,
    "income_trend": "stable",
    "market_maturity": "mature",
    "has_pool": false,
    "has_deck": true,
    "has_basement": false,
    "has_hoa": false,
    "num_garages": 1,
    "days_since_permit": 45,
    "days_since_violation": null,
    "business_owner": false
  },
  
  {
    // === LEAD 3: LUXURY PROPERTY ===
    "lead_id": "LEAD_003",
    "property_id": "PROP_003",
    "address": "789 Elm Drive, Phoenix, AZ 85001",
    "city": "Phoenix",
    "state": "AZ",
    "zip_code": "85001",
    "contact_name": "Mike Rodriguez",
    "phone": "602-555-0789",
    "email": "mike.rodriguez@yahoo.com",
    "property_value": 1200000,
    "purchase_price": 1150000,
    "market_value": 1200000,
    "year_built": 2020,
    "building_sqft": 4800,
    "lot_size_sqft": 21780,
    "lot_size_acres": 0.5,
    "bedrooms": 5,
    "bathrooms": 4,
    "property_type": "Single Family",
    "days_since_purchase": 30,
    "mortgage_amount": 920000,
    "property_tax_trend": "increasing",
    "estimated_income": 250000,
    "family_size": 5,
    "school_rating": 10,
    "neighborhood_type": "suburban",
    "neighborhood_value_trend": "increasing",
    "neighborhood_median_income": 180000,
    "competitor_count": 2,
    "population_density": 1800,
    "market_growth_rate": 15,
    "unemployment_rate": 3.2,
    "income_trend": "increasing",
    "market_maturity": "growing",
    "has_pool": true,
    "has_deck": true,
    "has_basement": false,
    "has_hoa": true,
    "num_garages": 3,
    "days_since_permit": 10,
    "days_since_violation": null,
    "business_owner": true
  },
  
  {
    // === LEAD 4: OLDER HOME NEEDING WORK ===
    "lead_id": "LEAD_004",
    "property_id": "PROP_004",
    "address": "321 Maple Lane, Denver, CO 80202",
    "city": "Denver",
    "state": "CO",
    "zip_code": "80202",
    "contact_name": "Emily Chen",
    "phone": "303-555-0321",
    "email": "emily.chen@outlook.com",
    "property_value": 320000,
    "purchase_price": 295000,
    "market_value": 320000,
    "year_built": 1985,
    "building_sqft": 1800,
    "lot_size_sqft": 6534,
    "lot_size_acres": 0.15,
    "bedrooms": 2,
    "bathrooms": 1,
    "property_type": "Single Family",
    "days_since_purchase": 180,
    "mortgage_amount": 236000,
    "property_tax_trend": "stable",
    "estimated_income": 65000,
    "family_size": 2,
    "school_rating": 6,
    "neighborhood_type": "urban",
    "neighborhood_value_trend": "stable",
    "neighborhood_median_income": 55000,
    "competitor_count": 12,
    "population_density": 6800,
    "market_growth_rate": 5,
    "unemployment_rate": 5.1,
    "income_trend": "stable",
    "market_maturity": "mature",
    "has_pool": false,
    "has_deck": false,
    "has_basement": true,
    "has_hoa": false,
    "num_garages": 1,
    "days_since_permit": 90,
    "days_since_violation": 15,
    "business_owner": false
  },
  
  {
    // === LEAD 5: CONDO IN HOT MARKET ===
    "lead_id": "LEAD_005",
    "property_id": "PROP_005",
    "address": "654 Cedar Court, Miami, FL 33101",
    "city": "Miami",
    "state": "FL",
    "zip_code": "33101",
    "contact_name": "David Wilson",
    "phone": "305-555-0654",
    "email": "david.wilson@hotmail.com",
    "property_value": 650000,
    "purchase_price": 620000,
    "market_value": 650000,
    "year_built": 2018,
    "building_sqft": 1600,
    "lot_size_sqft": 0,
    "lot_size_acres": 0,
    "bedrooms": 2,
    "bathrooms": 2,
    "property_type": "Condo",
    "days_since_purchase": 60,
    "mortgage_amount": 496000,
    "property_tax_trend": "increasing",
    "estimated_income": 110000,
    "family_size": 1,
    "school_rating": 7,
    "neighborhood_type": "urban",
    "neighborhood_value_trend": "increasing",
    "neighborhood_median_income": 95000,
    "competitor_count": 5,
    "population_density": 12000,
    "market_growth_rate": 18,
    "unemployment_rate": 4.5,
    "income_trend": "increasing",
    "market_maturity": "growing",
    "has_pool": true,
    "has_deck": false,
    "has_basement": false,
    "has_hoa": true,
    "num_garages": 1,
    "days_since_permit": 20,
    "days_since_violation": null,
    "business_owner": false
  }
];

console.log("=== COMPREHENSIVE TEST LEADS LOADED ===");
console.log("Total leads:", testLeads.length);
console.log("Lead types:");
console.log("1. High-value urgent lead (John Smith)");
console.log("2. Mid-value family home (Sarah Johnson)");
console.log("3. Luxury property (Mike Rodriguez)");
console.log("4. Older home needing work (Emily Chen)");
console.log("5. Condo in hot market (David Wilson)");

// Return in N8N format
return testLeads.map(lead => ({ json: lead }));
