// ENHANCED TEST DATA - Comprehensive Testing with Debugging
// This will help identify exactly where the data processing is failing

try {
  console.log("=== ENHANCED TEST DATA LOADING ===");
  
  // Enhanced test leads with debugging information
  const enhancedTestLeads = [
    {
      // LEAD 1: High-value recent purchase (should score high)
      "lead_id": "LEAD_001",
      "property_id": "PROP_001", 
      "address": "123 Oak Street, Chicago, IL 60614",
      "city": "Chicago",
      "state": "IL",
      "zip_code": "60614",
      "contact_name": "John Smith",
      "phone": "312-555-0123",
      "email": "john.smith@email.com",
      "property_value": 750000,
      "purchase_price": 720000,
      "market_value": 750000,
      "year_built": 2019,
      "building_sqft": 3500,
      "lot_size_sqft": 13068,
      "bedrooms": 4,
      "bathrooms": 3,
      "property_type": "Single Family",
      "days_since_purchase": 45,
      "mortgage_amount": 576000,
      "property_tax_trend": "increasing",
      "estimated_income": 150000,
      "family_size": 4,
      "school_rating": 9,
      "neighborhood_type": "suburban",
      "neighborhood_value_trend": "increasing",
      "neighborhood_median_income": 120000,
      "competitor_count": 3,
      "population_density": 2500,
      "market_growth_rate": 12,
      "unemployment_rate": 4.2,
      "income_trend": "increasing",
      "market_maturity": "growing",
      "has_pool": true,
      "has_deck": false,
      "has_basement": true,
      "has_hoa": true,
      "num_garages": 2,
      "days_since_permit": 15,
      "days_since_violation": null,
      "business_owner": false,
      "test_lead_type": "HIGH_VALUE_RECENT"
    },
    {
      // LEAD 2: Moderate value, established homeowner (should score medium)
      "lead_id": "LEAD_002",
      "property_id": "PROP_002",
      "address": "456 Pine Avenue, Austin, TX 78701",
      "city": "Austin",
      "state": "TX",
      "zip_code": "78701",
      "contact_name": "Sarah Johnson",
      "phone": "512-555-0456",
      "email": "sarah.johnson@email.com",
      "property_value": 450000,
      "purchase_price": 430000,
      "market_value": 450000,
      "year_built": 2015,
      "building_sqft": 2200,
      "lot_size_sqft": 8712,
      "bedrooms": 3,
      "bathrooms": 2,
      "property_type": "Single Family",
      "days_since_purchase": 120,
      "mortgage_amount": 344000,
      "property_tax_trend": "stable",
      "estimated_income": 95000,
      "family_size": 2,
      "school_rating": 7,
      "neighborhood_type": "urban",
      "neighborhood_value_trend": "stable",
      "neighborhood_median_income": 85000,
      "competitor_count": 8,
      "population_density": 4500,
      "market_growth_rate": 6,
      "unemployment_rate": 5.8,
      "income_trend": "stable",
      "market_maturity": "mature",
      "has_pool": false,
      "has_deck": true,
      "has_basement": false,
      "has_hoa": false,
      "num_garages": 1,
      "days_since_permit": 90,
      "days_since_violation": null,
      "business_owner": true,
      "test_lead_type": "MODERATE_VALUE_ESTABLISHED"
    },
    {
      // LEAD 3: Lower value, older purchase (should score lower)
      "lead_id": "LEAD_003",
      "property_id": "PROP_003",
      "address": "789 Elm Drive, Phoenix, AZ 85001",
      "city": "Phoenix",
      "state": "AZ",
      "zip_code": "85001",
      "contact_name": "Mike Rodriguez",
      "phone": "602-555-0789",
      "email": "mike.rodriguez@email.com",
      "property_value": 320000,
      "purchase_price": 310000,
      "market_value": 320000,
      "year_built": 2008,
      "building_sqft": 1800,
      "lot_size_sqft": 6534,
      "bedrooms": 3,
      "bathrooms": 2,
      "property_type": "Single Family",
      "days_since_purchase": 300,
      "mortgage_amount": 248000,
      "property_tax_trend": "increasing",
      "estimated_income": 75000,
      "family_size": 3,
      "school_rating": 6,
      "neighborhood_type": "suburban",
      "neighborhood_value_trend": "increasing",
      "neighborhood_median_income": 70000,
      "competitor_count": 12,
      "population_density": 3200,
      "market_growth_rate": 8,
      "unemployment_rate": 6.5,
      "income_trend": "increasing",
      "market_maturity": "growing",
      "has_pool": false,
      "has_deck": false,
      "has_basement": false,
      "has_hoa": true,
      "num_garages": 2,
      "days_since_permit": null,
      "days_since_violation": 45,
      "business_owner": false,
      "test_lead_type": "LOWER_VALUE_OLDER"
    },
    {
      // LEAD 4: Premium value, very recent purchase (should score highest)
      "lead_id": "LEAD_004",
      "property_id": "PROP_004",
      "address": "321 Maple Street, Denver, CO 80202",
      "city": "Denver",
      "state": "CO",
      "zip_code": "80202",
      "contact_name": "Emily Chen",
      "phone": "303-555-0321",
      "email": "emily.chen@email.com",
      "property_value": 680000,
      "purchase_price": 650000,
      "market_value": 680000,
      "year_built": 2020,
      "building_sqft": 2800,
      "lot_size_sqft": 10890,
      "bedrooms": 4,
      "bathrooms": 3,
      "property_type": "Single Family",
      "days_since_purchase": 15,
      "mortgage_amount": 520000,
      "property_tax_trend": "increasing",
      "estimated_income": 180000,
      "family_size": 3,
      "school_rating": 10,
      "neighborhood_type": "suburban",
      "neighborhood_value_trend": "increasing_fast",
      "neighborhood_median_income": 160000,
      "competitor_count": 2,
      "population_density": 1800,
      "market_growth_rate": 18,
      "unemployment_rate": 3.1,
      "income_trend": "increasing_fast",
      "market_maturity": "emerging",
      "has_pool": true,
      "has_deck": true,
      "has_basement": true,
      "has_hoa": true,
      "num_garages": 3,
      "days_since_permit": 5,
      "days_since_violation": null,
      "business_owner": true,
      "test_lead_type": "PREMIUM_VALUE_RECENT"
    },
    {
      // LEAD 5: Mid-value, moderate purchase age (should score medium-high)
      "lead_id": "LEAD_005",
      "property_id": "PROP_005",
      "address": "654 Birch Lane, Miami, FL 33101",
      "city": "Miami",
      "state": "FL",
      "zip_code": "33101",
      "contact_name": "David Martinez",
      "phone": "305-555-0654",
      "email": "david.martinez@email.com",
      "property_value": 520000,
      "purchase_price": 500000,
      "market_value": 520000,
      "year_built": 2012,
      "building_sqft": 2400,
      "lot_size_sqft": 8712,
      "bedrooms": 3,
      "bathrooms": 2,
      "property_type": "Single Family",
      "days_since_purchase": 200,
      "mortgage_amount": 400000,
      "property_tax_trend": "stable",
      "estimated_income": 110000,
      "family_size": 2,
      "school_rating": 8,
      "neighborhood_type": "suburban",
      "neighborhood_value_trend": "stable",
      "neighborhood_median_income": 95000,
      "competitor_count": 15,
      "population_density": 4200,
      "market_growth_rate": 4,
      "unemployment_rate": 7.2,
      "income_trend": "stable",
      "market_maturity": "mature",
      "has_pool": true,
      "has_deck": false,
      "has_basement": false,
      "has_hoa": true,
      "num_garages": 2,
      "days_since_permit": 60,
      "days_since_violation": null,
      "business_owner": false,
      "test_lead_type": "MID_VALUE_MODERATE"
    }
  ];
  
  console.log("Loaded", enhancedTestLeads.length, "test leads");
  console.log("Lead types:", enhancedTestLeads.map(lead => lead.test_lead_type));
  
  // Return all leads for processing
  const output = enhancedTestLeads.map(lead => ({ json: lead }));
  
  console.log("Returning", output.length, "items for processing");
  console.log("First item contact name:", output[0].json.contact_name);
  console.log("Last item contact name:", output[output.length - 1].json.contact_name);
  
  return output;
  
} catch (error) {
  console.error("ERROR in Enhanced Test Data:", error);
  
  // Return error data
  return [{
    json: {
      lead_id: "ERROR_001",
      contact_name: "ERROR",
      address: "ERROR",
      property_value: 0,
      error: error.message,
      test_lead_type: "ERROR"
    }
  }];
}
