// N8N TEST DATA LOADER - Load 10 test properties
// Use this instead of HTTP Request for testing

const testProperties = [
  {
    "id": 1,
    "Address": "123 Oak Street",
    "City": "Chicago",
    "State": "IL",
    "Zip": "60614",
    "Living Square Feet": 3500,
    "Year Built": 2019,
    "Lot (Acres)": 0.3,
    "Property Type": "Single Family",
    "Bedrooms": 4,
    "Bathrooms": 3,
    "Owner 1 Last Name": "Smith",
    "Last Sale Date": "2024-08-15",
    "Last Sale Amount": 750000,
    "Estimated Value": 750000,
    "Has Pool": true,
    "Has HOA": true,
    "Has Deck": true,
    "Has Basement": false,
    "Garages": 2,
    "Estimated Income": 150000,
    "School Rating": 9,
    "Neighborhood Type": "suburban",
    "Property Tax Trend": "increasing",
    "Neighborhood Value Trend": "increasing",
    "Competitor Count": 3,
    "Population Density": 2500,
    "Market Growth Rate": 8,
    "Unemployment Rate": 4,
    "Income Trend": "increasing",
    "Market Maturity": "mature"
  },
  {
    "id": 2,
    "Address": "456 Maple Avenue",
    "City": "Chicago",
    "State": "IL",
    "Zip": "60610",
    "Living Square Feet": 2800,
    "Year Built": 1995,
    "Lot (Acres)": 0.2,
    "Property Type": "Single Family",
    "Bedrooms": 3,
    "Bathrooms": 2,
    "Owner 1 Last Name": "Johnson",
    "Last Sale Date": "2022-06-20",
    "Last Sale Amount": 450000,
    "Estimated Value": 450000,
    "Has Pool": false,
    "Has HOA": false,
    "Has Deck": false,
    "Has Basement": true,
    "Garages": 1,
    "Estimated Income": 85000,
    "School Rating": 7,
    "Neighborhood Type": "urban",
    "Property Tax Trend": "stable",
    "Neighborhood Value Trend": "stable",
    "Competitor Count": 5,
    "Population Density": 4000,
    "Market Growth Rate": 5,
    "Unemployment Rate": 5,
    "Income Trend": "stable",
    "Market Maturity": "mature"
  },
  {
    "id": 3,
    "Address": "789 Pine Street",
    "City": "Chicago",
    "State": "IL",
    "Zip": "60611",
    "Living Square Feet": 2200,
    "Year Built": 2010,
    "Lot (Acres)": 0.15,
    "Property Type": "Townhouse",
    "Bedrooms": 3,
    "Bathrooms": 2,
    "Owner 1 Last Name": "Davis",
    "Last Sale Date": "2024-03-10",
    "Last Sale Amount": 320000,
    "Estimated Value": 320000,
    "Has Pool": false,
    "Has HOA": true,
    "Has Deck": false,
    "Has Basement": false,
    "Garages": 1,
    "Estimated Income": 95000,
    "School Rating": 8,
    "Neighborhood Type": "suburban",
    "Property Tax Trend": "increasing",
    "Neighborhood Value Trend": "increasing",
    "Competitor Count": 2,
    "Population Density": 2000,
    "Market Growth Rate": 12,
    "Unemployment Rate": 3,
    "Income Trend": "increasing",
    "Market Maturity": "growing"
  },
  {
    "id": 4,
    "Address": "321 Elm Drive",
    "City": "Chicago",
    "State": "IL",
    "Zip": "60615",
    "Living Square Feet": 4500,
    "Year Built": 1929,
    "Lot (Acres)": 0.5,
    "Property Type": "Single Family",
    "Bedrooms": 5,
    "Bathrooms": 4,
    "Owner 1 Last Name": "Wilson",
    "Last Sale Date": "2024-01-05",
    "Last Sale Amount": 650000,
    "Estimated Value": 650000,
    "Has Pool": true,
    "Has HOA": true,
    "Has Deck": true,
    "Has Basement": true,
    "Garages": 3,
    "Estimated Income": 180000,
    "School Rating": 9,
    "Neighborhood Type": "suburban",
    "Property Tax Trend": "increasing",
    "Neighborhood Value Trend": "increasing",
    "Competitor Count": 2,
    "Population Density": 1500,
    "Market Growth Rate": 15,
    "Unemployment Rate": 3,
    "Income Trend": "increasing_fast",
    "Market Maturity": "emerging"
  },
  {
    "id": 5,
    "Address": "654 Cedar Lane",
    "City": "Chicago",
    "State": "IL",
    "Zip": "60612",
    "Living Square Feet": 1800,
    "Year Built": 1985,
    "Lot (Acres)": 0.25,
    "Property Type": "Single Family",
    "Bedrooms": 3,
    "Bathrooms": 2,
    "Owner 1 Last Name": "Brown",
    "Last Sale Date": "2023-11-15",
    "Last Sale Amount": 380000,
    "Estimated Value": 380000,
    "Has Pool": false,
    "Has HOA": false,
    "Has Deck": true,
    "Has Basement": false,
    "Garages": 2,
    "Estimated Income": 75000,
    "School Rating": 6,
    "Neighborhood Type": "urban",
    "Property Tax Trend": "stable",
    "Neighborhood Value Trend": "stable",
    "Competitor Count": 6,
    "Population Density": 3500,
    "Market Growth Rate": 3,
    "Unemployment Rate": 6,
    "Income Trend": "stable",
    "Market Maturity": "mature"
  },
  {
    "id": 6,
    "Address": "987 Birch Court",
    "City": "Chicago",
    "State": "IL",
    "Zip": "60613",
    "Living Square Feet": 3200,
    "Year Built": 2005,
    "Lot (Acres)": 0.4,
    "Property Type": "Single Family",
    "Bedrooms": 4,
    "Bathrooms": 3,
    "Owner 1 Last Name": "Miller",
    "Last Sale Date": "2024-07-30",
    "Last Sale Amount": 520000,
    "Estimated Value": 520000,
    "Has Pool": true,
    "Has HOA": false,
    "Has Deck": true,
    "Has Basement": true,
    "Garages": 2,
    "Estimated Income": 120000,
    "School Rating": 8,
    "Neighborhood Type": "suburban",
    "Property Tax Trend": "increasing",
    "Neighborhood Value Trend": "increasing",
    "Competitor Count": 4,
    "Population Density": 2200,
    "Market Growth Rate": 7,
    "Unemployment Rate": 4,
    "Income Trend": "increasing",
    "Market Maturity": "mature"
  },
  {
    "id": 7,
    "Address": "147 Spruce Way",
    "City": "Chicago",
    "State": "IL",
    "Zip": "60614",
    "Living Square Feet": 2500,
    "Year Built": 1998,
    "Lot (Acres)": 0.3,
    "Property Type": "Single Family",
    "Bedrooms": 3,
    "Bathrooms": 2,
    "Owner 1 Last Name": "Garcia",
    "Last Sale Date": "2023-09-12",
    "Last Sale Amount": 420000,
    "Estimated Value": 420000,
    "Has Pool": false,
    "Has HOA": true,
    "Has Deck": false,
    "Has Basement": false,
    "Garages": 1,
    "Estimated Income": 90000,
    "School Rating": 7,
    "Neighborhood Type": "suburban",
    "Property Tax Trend": "stable",
    "Neighborhood Value Trend": "increasing",
    "Competitor Count": 3,
    "Population Density": 1800,
    "Market Growth Rate": 6,
    "Unemployment Rate": 4,
    "Income Trend": "stable",
    "Market Maturity": "mature"
  },
  {
    "id": 8,
    "Address": "258 Ash Street",
    "City": "Chicago",
    "State": "IL",
    "Zip": "60610",
    "Living Square Feet": 1900,
    "Year Built": 2015,
    "Lot (Acres)": 0.2,
    "Property Type": "Condo",
    "Bedrooms": 2,
    "Bathrooms": 2,
    "Owner 1 Last Name": "Martinez",
    "Last Sale Date": "2024-05-18",
    "Last Sale Amount": 290000,
    "Estimated Value": 290000,
    "Has Pool": false,
    "Has HOA": true,
    "Has Deck": false,
    "Has Basement": false,
    "Garages": 1,
    "Estimated Income": 65000,
    "School Rating": 6,
    "Neighborhood Type": "urban",
    "Property Tax Trend": "stable",
    "Neighborhood Value Trend": "stable",
    "Competitor Count": 8,
    "Population Density": 4500,
    "Market Growth Rate": 2,
    "Unemployment Rate": 7,
    "Income Trend": "stable",
    "Market Maturity": "mature"
  },
  {
    "id": 9,
    "Address": "369 Willow Road",
    "City": "Chicago",
    "State": "IL",
    "Zip": "60611",
    "Living Square Feet": 4100,
    "Year Built": 1975,
    "Lot (Acres)": 0.6,
    "Property Type": "Single Family",
    "Bedrooms": 5,
    "Bathrooms": 4,
    "Owner 1 Last Name": "Anderson",
    "Last Sale Date": "2024-02-28",
    "Last Sale Amount": 580000,
    "Estimated Value": 580000,
    "Has Pool": true,
    "Has HOA": false,
    "Has Deck": true,
    "Has Basement": true,
    "Garages": 3,
    "Estimated Income": 140000,
    "School Rating": 8,
    "Neighborhood Type": "suburban",
    "Property Tax Trend": "increasing",
    "Neighborhood Value Trend": "increasing",
    "Competitor Count": 1,
    "Population Density": 1200,
    "Market Growth Rate": 18,
    "Unemployment Rate": 2,
    "Income Trend": "increasing_fast",
    "Market Maturity": "growing"
  },
  {
    "id": 10,
    "Address": "741 Poplar Avenue",
    "City": "Chicago",
    "State": "IL",
    "Zip": "60612",
    "Living Square Feet": 2100,
    "Year Built": 2000,
    "Lot (Acres)": 0.25,
    "Property Type": "Single Family",
    "Bedrooms": 3,
    "Bathrooms": 2,
    "Owner 1 Last Name": "Taylor",
    "Last Sale Date": "2023-12-03",
    "Last Sale Amount": 350000,
    "Estimated Value": 350000,
    "Has Pool": false,
    "Has HOA": false,
    "Has Deck": false,
    "Has Basement": true,
    "Garages": 2,
    "Estimated Income": 80000,
    "School Rating": 7,
    "Neighborhood Type": "urban",
    "Property Tax Trend": "stable",
    "Neighborhood Value Trend": "stable",
    "Competitor Count": 5,
    "Population Density": 3000,
    "Market Growth Rate": 4,
    "Unemployment Rate": 5,
    "Income Trend": "stable",
    "Market Maturity": "mature"
  }
];

// Return the test data as N8N items
return testProperties.map(property => ({ json: property }));
